steps:
- task: PublishCodeCoverageResults@1
  displayName: "Publish code coverage"
  inputs:
    summaryFileLocation: $(System.DefaultWorkingDirectory)/tratto/target/site/jacoco/jacoco.xml
    pathToSources: $(System.DefaultWorkingDirectory)/tratto/src/main/java/