/**
 * The star.tratto.oraclegrammar package is automatically generated by the Xtext project containing
 * the TrattoGrammar class and associated functionality. This "custom" subpackage contains additional
 * functionality manually implemented needed to handle oracles written in TrattoGrammar.
 */
package star.tratto.oraclegrammar.custom;