/**
 * The star.tratto.oraclegrammar package is automatically generated by the Xtext project containing
 * the TrattoGrammar class and associated functionality. This "custom" subpackage contains additional
 * functionality manually implemented needed to handle oracles written in TrattoGrammar.
 * <br><br>
 * NOTE: For reference everywhere in this project: "jdVar" is a special type of token of TrattoGrammar
 * that stands for "JDoctor variable" (called in this way for legacy reasons). It is a special
 * variable name that can only and must always be used as the parameter of a lambda expression when
 * dealing with arrays and lists, for instance, {@code Arrays.stream(array).noneMatch(jdVar -> ...)}.
 */
package star.tratto.oraclegrammar.custom;