
pool:
  vmImage: ubuntu-latest
jobs:
- job: unit_tests
  steps:
  - task: ShellScript@2
    displayName: "Install TrattoGrammar dependency"
    inputs:
      scriptPath: 'tratto/scripts/install_dependencies.sh'
  - task: Maven@3
    displayName: "Build and run tests"
    inputs:
      mavenPomFile: 'tratto/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage"
    inputs:
      summaryFileLocation: $(System.DefaultWorkingDirectory)/tratto/target/site/jacoco/jacoco.xml
      pathToSources: $(System.DefaultWorkingDirectory)/tratto/src/main/java/
- job: tokensuggester_e2e_tests
  dependsOn:
  - unit_tests
  steps:
  - task: Maven@3
    displayName: "Run TokenSuggester E2E tests"
    inputs:
      mavenPomFile: 'tratto/pom.xml'
      mavenOptions: '-Dtest=star.tratto.E2ETests#tokenSuggesterE2ETest'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'test'
  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage"
    inputs:
      summaryFileLocation: $(System.DefaultWorkingDirectory)/tratto/target/site/jacoco/jacoco.xml
      pathToSources: $(System.DefaultWorkingDirectory)/tratto/src/main/java/
- job: datasets_e2e_tests
  dependsOn:
  - unit_tests
  steps:
  - task: Maven@3
    displayName: "Run datasets E2E tests"
    inputs:
      mavenPomFile: 'tratto/pom.xml'
      mavenOptions: '-Dtest=star.tratto.E2ETests#datasetsE2ETest'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'test'
  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage"
    inputs:
      summaryFileLocation: $(System.DefaultWorkingDirectory)/tratto/target/site/jacoco/jacoco.xml
      pathToSources: $(System.DefaultWorkingDirectory)/tratto/src/main/java/