/**
 * This package contains classes featuring main() methods that are supposed to be
 * run on the oracles and tokens datasets generated by {@link star.tratto.OraclesDataset}
 * and {@link star.tratto.TokensDataset}. This is done to preprocess such datasets,
 * generate alternate versions (e.g., needed for the binary oracle classifier) or
 * augment them.
 * <br>
 * Disclaimer: These classes may not be thoroughly unit tested, as they generate
 * output files that are generally manually inspected.
 */
package star.tratto.preprocessing;