/*
 * generated by Xtext 2.29.0
 */
package star.tratto.oraclegrammar.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TrattoGrammarUiModule extends AbstractTrattoGrammarUiModule {

	public TrattoGrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
