/*
 * generated by Xtext 2.29.0
 */
package star.tratto.oraclegrammar.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class TrattoGrammarProposalProvider extends AbstractTrattoGrammarProposalProvider {
}
