export PYTHONPATH="./"
python scripts/test/run_classifier_decoder.py \
--do_train \
--do_eval \
--do_predict \
--model_type codet5+ \
--tokenizer_name Salesforce/codet5p-220m \
--model_name_or_path Salesforce/codet5p-220m \
--tratto_model_type token_classes \
--task_name tokenClasses_classifier \
--max_seq_length 512 \
--batch_size 24 \
--learning_rate 1e-5 \
--num_epochs 20 \
--save_steps 500 \
--accumulation_steps 1 \
--test_ratio 0.1 \
--validation_ratio 0.1 \
--data_dir ./dataset/token-classes-dataset \
--output_dir ./output_token_classes_decoder \
--classification_type category_prediction