/*
 * generated by Xtext 2.29.0
 */
package star.tratto.oraclegrammar.ide;


/**
 * Use this class to register ide components.
 */
public class TrattoGrammarIdeModule extends AbstractTrattoGrammarIdeModule {
}
